<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="8" total="20" passed="0" failed="12" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[====CHROME IS LAUNCHED SUCCESSFULLY====]]>
    </line>
    <line>
      <![CDATA[======Login is Successfull=====]]>
    </line>
    <line>
      <![CDATA[=====BROWSER IS CLOSED======]]>
    </line>
    <line>
      <![CDATA[====CHROME IS LAUNCHED SUCCESSFULLY====]]>
    </line>
    <line>
      <![CDATA[======Login is Successfull=====]]>
    </line>
    <line>
      <![CDATA[order is posted successfully]]>
    </line>
    <line>
      <![CDATA[======Login is Successfull=====]]>
    </line>
    <line>
      <![CDATA[=====BROWSER IS CLOSED======]]>
    </line>
    <line>
      <![CDATA[======Login is Successfull=====]]>
    </line>
    <line>
      <![CDATA[=====BROWSER IS CLOSED======]]>
    </line>
    <line>
      <![CDATA[=====BROWSER IS CLOSED======]]>
    </line>
    <line>
      <![CDATA[====CHROME IS LAUNCHED SUCCESSFULLY====]]>
    </line>
    <line>
      <![CDATA[======Login is Successfull=====]]>
    </line>
    <line>
      <![CDATA[======Login is Successfull=====]]>
    </line>
    <line>
      <![CDATA[=====BROWSER IS CLOSED======]]>
    </line>
    <line>
      <![CDATA[=====BROWSER IS CLOSED======]]>
    </line>
  </reporter-output>
  <suite started-at="2024-11-26T10:54:10 IST" name="crossBrowserSuite" finished-at="2024-11-26T10:54:49 IST" duration-ms="38704">
    <groups>
      <group name="integration">
        <method signature="Admin.addProduct()[pri:0, instance:smartChainTestCase.Admin@298a5e20]" name="addProduct" class="smartChainTestCase.Admin"/>
        <method signature="Admin.editManageStock()[pri:0, instance:smartChainTestCase.Admin@298a5e20]" name="editManageStock" class="smartChainTestCase.Admin"/>
        <method signature="Manufacturer.manageStock()[pri:0, instance:smartChainTestCase.Manufacturer@54c5a2ff]" name="manageStock" class="smartChainTestCase.Manufacturer"/>
        <method signature="Retailer.order_Manufacturer()[pri:0, instance:smartChainTestCase.Retailer@1ed4ae0f]" name="order_Manufacturer" class="smartChainTestCase.Retailer"/>
        <method signature="Admin.addProduct()[pri:0, instance:smartChainTestCase.Admin@79e4c792]" name="addProduct" class="smartChainTestCase.Admin"/>
        <method signature="Admin.editManageStock()[pri:0, instance:smartChainTestCase.Admin@79e4c792]" name="editManageStock" class="smartChainTestCase.Admin"/>
        <method signature="Manufacturer.manageStock()[pri:0, instance:smartChainTestCase.Manufacturer@4c60d6e9]" name="manageStock" class="smartChainTestCase.Manufacturer"/>
        <method signature="Retailer.order_Manufacturer()[pri:0, instance:smartChainTestCase.Retailer@196a42c3]" name="order_Manufacturer" class="smartChainTestCase.Retailer"/>
      </group> <!-- integration -->
      <group name="smoke">
        <method signature="Admin.addArea()[pri:0, instance:smartChainTestCase.Admin@298a5e20]" name="addArea" class="smartChainTestCase.Admin"/>
        <method signature="Retailer.retailer_myorders()[pri:0, instance:smartChainTestCase.Retailer@1ed4ae0f]" name="retailer_myorders" class="smartChainTestCase.Retailer"/>
        <method signature="Admin.addArea()[pri:0, instance:smartChainTestCase.Admin@79e4c792]" name="addArea" class="smartChainTestCase.Admin"/>
        <method signature="Retailer.retailer_myorders()[pri:0, instance:smartChainTestCase.Retailer@196a42c3]" name="retailer_myorders" class="smartChainTestCase.Retailer"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2024-11-26T10:54:10 IST" name="TestRunner_Firefox" finished-at="2024-11-26T10:54:47 IST" duration-ms="37349">
      <class name="smartChainTestCase.Manufacturer">
        <test-method is-config="true" signature="launchBrowser(java.lang.String)[pri:0, instance:smartChainTestCase.Manufacturer@4c60d6e9]" started-at="2024-11-26T10:54:32 IST" name="launchBrowser" finished-at="2024-11-26T10:54:38 IST" duration-ms="5483" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="manageStock()[pri:0, instance:smartChainTestCase.Manufacturer@4c60d6e9]" started-at="2024-11-26T10:54:38 IST" name="manageStock" finished-at="2024-11-26T10:54:45 IST" duration-ms="7341" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title miss match! expected [Manage Stock] but found [Admin: Home]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title miss match! expected [Manage Stock] but found [Admin: Home]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.SCM.assertUtility.Assertutility.verifyTitle(Assertutility.java:33)
at smartChainTestCase.Manufacturer.manageStock(Manufacturer.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[======Login is Successfull=====]]>
            </line>
          </reporter-output>
        </test-method> <!-- manageStock -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:smartChainTestCase.Manufacturer@4c60d6e9]" started-at="2024-11-26T10:54:45 IST" name="closeBrowser" finished-at="2024-11-26T10:54:47 IST" duration-ms="1862" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[=====BROWSER IS CLOSED======]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- smartChainTestCase.Manufacturer -->
      <class name="smartChainTestCase.Admin">
        <test-method is-config="true" signature="connectToDB()[pri:0, instance:smartChainTestCase.Admin@79e4c792]" started-at="2024-11-26T10:54:10 IST" name="connectToDB" finished-at="2024-11-26T10:54:10 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- connectToDB -->
        <test-method is-config="true" signature="launchBrowser(java.lang.String)[pri:0, instance:smartChainTestCase.Admin@79e4c792]" started-at="2024-11-26T10:54:10 IST" name="launchBrowser" finished-at="2024-11-26T10:54:20 IST" duration-ms="9973" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="addArea()[pri:0, instance:smartChainTestCase.Admin@79e4c792]" started-at="2024-11-26T10:54:20 IST" name="addArea" finished-at="2024-11-26T10:54:23 IST" duration-ms="3056" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title miss match! expected [Add Area] but found [Add Unit]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title miss match! expected [Add Area] but found [Add Unit]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.SCM.assertUtility.Assertutility.verifyTitle(Assertutility.java:33)
at smartChainTestCase.Admin.addArea(Admin.java:100)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[======Login is Successfull=====]]>
            </line>
          </reporter-output>
        </test-method> <!-- addArea -->
        <test-method signature="addProduct()[pri:0, instance:smartChainTestCase.Admin@79e4c792]" started-at="2024-11-26T10:54:23 IST" name="addProduct" finished-at="2024-11-26T10:54:23 IST" duration-ms="10" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title miss match! expected [Login] but found [Add Unit]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title miss match! expected [Login] but found [Add Unit]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.SCM.assertUtility.Assertutility.verifyTitle(Assertutility.java:33)
at smartChainTestCase.Admin.addProduct(Admin.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addProduct -->
        <test-method signature="editManageStock()[pri:0, instance:smartChainTestCase.Admin@79e4c792]" started-at="2024-11-26T10:54:23 IST" name="editManageStock" finished-at="2024-11-26T10:54:23 IST" duration-ms="7" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title miss match! expected [Login] but found [Add Unit]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title miss match! expected [Login] but found [Add Unit]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.SCM.assertUtility.Assertutility.verifyTitle(Assertutility.java:33)
at smartChainTestCase.Admin.editManageStock(Admin.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editManageStock -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:smartChainTestCase.Admin@79e4c792]" started-at="2024-11-26T10:54:23 IST" name="closeBrowser" finished-at="2024-11-26T10:54:24 IST" duration-ms="1482" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[=====BROWSER IS CLOSED======]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="closeDB()[pri:0, instance:smartChainTestCase.Admin@79e4c792]" started-at="2024-11-26T10:54:49 IST" name="closeDB" finished-at="2024-11-26T10:54:49 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDB -->
      </class> <!-- smartChainTestCase.Admin -->
      <class name="smartChainTestCase.Retailer">
        <test-method is-config="true" signature="launchBrowser(java.lang.String)[pri:0, instance:smartChainTestCase.Retailer@196a42c3]" started-at="2024-11-26T10:54:24 IST" name="launchBrowser" finished-at="2024-11-26T10:54:29 IST" duration-ms="4795" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="order_Manufacturer()[pri:0, instance:smartChainTestCase.Retailer@196a42c3]" started-at="2024-11-26T10:54:29 IST" name="order_Manufacturer" finished-at="2024-11-26T10:54:31 IST" duration-ms="2088" status="FAIL">
          <exception class="org.openqa.selenium.ElementClickInterceptedException">
            <message>
              <![CDATA[Element <input id="btnSubmit" class="submit_button" type="submit"> is not clickable at point (406,715) because another element <div> obscures it
Build info: version: '4.12.0', revision: '249f2a7d1b*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [02d03e7a-3f0a-4363-aca8-9aaee17559bd, clickElement {id=d109b82e-2624-406b-9279-411c78f496fa}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 132.0.2, moz:accessibilityChecks: false, moz:buildID: 20241110231641, moz:geckodriverVersion: 0.35.0, moz:headless: false, moz:platformVersion: 10.0, moz:processID: 2160, moz:profile: C:\Users\Ranjith\AppData\Lo..., moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, userAgent: Mozilla/5.0 (Windows NT 10....}
Element: [[FirefoxDriver: firefox on windows (02d03e7a-3f0a-4363-aca8-9aaee17559bd)] -> xpath: //input[@value='Post Order']]
Session ID: 02d03e7a-3f0a-4363-aca8-9aaee17559bd]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.ElementClickInterceptedException: Element <input id="btnSubmit" class="submit_button" type="submit"> is not clickable at point (406,715) because another element <div> obscures it
Build info: version: '4.12.0', revision: '249f2a7d1b*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [02d03e7a-3f0a-4363-aca8-9aaee17559bd, clickElement {id=d109b82e-2624-406b-9279-411c78f496fa}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 132.0.2, moz:accessibilityChecks: false, moz:buildID: 20241110231641, moz:geckodriverVersion: 0.35.0, moz:headless: false, moz:platformVersion: 10.0, moz:processID: 2160, moz:profile: C:\Users\Ranjith\AppData\Lo..., moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, userAgent: Mozilla/5.0 (Windows NT 10....}
Element: [[FirefoxDriver: firefox on windows (02d03e7a-3f0a-4363-aca8-9aaee17559bd)] -> xpath: //input[@value='Post Order']]
Session ID: 02d03e7a-3f0a-4363-aca8-9aaee17559bd
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:224)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy20.click(Unknown Source)
at com.smart.ObjectRepository.OrderItemsPage.placeOrder(OrderItemsPage.java:34)
at smartChainTestCase.Retailer.order_Manufacturer(Retailer.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.ElementClickInterceptedException -->
          <reporter-output>
            <line>
              <![CDATA[======Login is Successfull=====]]>
            </line>
          </reporter-output>
        </test-method> <!-- order_Manufacturer -->
        <test-method signature="retailer_myorders()[pri:0, instance:smartChainTestCase.Retailer@196a42c3]" started-at="2024-11-26T10:54:31 IST" name="retailer_myorders" finished-at="2024-11-26T10:54:31 IST" duration-ms="6" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title miss match! expected [Login] but found [Order Items]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title miss match! expected [Login] but found [Order Items]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.SCM.assertUtility.Assertutility.verifyTitle(Assertutility.java:33)
at smartChainTestCase.Retailer.retailer_myorders(Retailer.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- retailer_myorders -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:smartChainTestCase.Retailer@196a42c3]" started-at="2024-11-26T10:54:31 IST" name="closeBrowser" finished-at="2024-11-26T10:54:32 IST" duration-ms="1167" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[=====BROWSER IS CLOSED======]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- smartChainTestCase.Retailer -->
    </test> <!-- TestRunner_Firefox -->
    <test started-at="2024-11-26T10:54:10 IST" name="TestRunner_Chrome" finished-at="2024-11-26T10:54:49 IST" duration-ms="38704">
      <class name="smartChainTestCase.Manufacturer">
        <test-method is-config="true" signature="launchBrowser(java.lang.String)[pri:0, instance:smartChainTestCase.Manufacturer@54c5a2ff]" started-at="2024-11-26T10:54:36 IST" name="launchBrowser" finished-at="2024-11-26T10:54:40 IST" duration-ms="3601" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[====CHROME IS LAUNCHED SUCCESSFULLY====]]>
            </line>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="manageStock()[pri:0, instance:smartChainTestCase.Manufacturer@54c5a2ff]" started-at="2024-11-26T10:54:40 IST" name="manageStock" finished-at="2024-11-26T10:54:48 IST" duration-ms="7854" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title miss match! expected [Manage Stock] but found [Admin: Home]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title miss match! expected [Manage Stock] but found [Admin: Home]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.SCM.assertUtility.Assertutility.verifyTitle(Assertutility.java:33)
at smartChainTestCase.Manufacturer.manageStock(Manufacturer.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[======Login is Successfull=====]]>
            </line>
          </reporter-output>
        </test-method> <!-- manageStock -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:smartChainTestCase.Manufacturer@54c5a2ff]" started-at="2024-11-26T10:54:48 IST" name="closeBrowser" finished-at="2024-11-26T10:54:49 IST" duration-ms="672" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[=====BROWSER IS CLOSED======]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- smartChainTestCase.Manufacturer -->
      <class name="smartChainTestCase.Admin">
        <test-method is-config="true" signature="launchBrowser(java.lang.String)[pri:0, instance:smartChainTestCase.Admin@298a5e20]" started-at="2024-11-26T10:54:10 IST" name="launchBrowser" finished-at="2024-11-26T10:54:14 IST" duration-ms="4589" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[====CHROME IS LAUNCHED SUCCESSFULLY====]]>
            </line>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="addArea()[pri:0, instance:smartChainTestCase.Admin@298a5e20]" started-at="2024-11-26T10:54:14 IST" name="addArea" finished-at="2024-11-26T10:54:16 IST" duration-ms="1614" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title miss match! expected [Add Area] but found [Add Unit]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title miss match! expected [Add Area] but found [Add Unit]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.SCM.assertUtility.Assertutility.verifyTitle(Assertutility.java:33)
at smartChainTestCase.Admin.addArea(Admin.java:100)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[======Login is Successfull=====]]>
            </line>
          </reporter-output>
        </test-method> <!-- addArea -->
        <test-method signature="addProduct()[pri:0, instance:smartChainTestCase.Admin@298a5e20]" started-at="2024-11-26T10:54:16 IST" name="addProduct" finished-at="2024-11-26T10:54:16 IST" duration-ms="13" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title miss match! expected [Login] but found [Add Unit]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title miss match! expected [Login] but found [Add Unit]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.SCM.assertUtility.Assertutility.verifyTitle(Assertutility.java:33)
at smartChainTestCase.Admin.addProduct(Admin.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addProduct -->
        <test-method signature="editManageStock()[pri:0, instance:smartChainTestCase.Admin@298a5e20]" started-at="2024-11-26T10:54:16 IST" name="editManageStock" finished-at="2024-11-26T10:54:16 IST" duration-ms="18" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title miss match! expected [Login] but found [Add Unit]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title miss match! expected [Login] but found [Add Unit]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.SCM.assertUtility.Assertutility.verifyTitle(Assertutility.java:33)
at smartChainTestCase.Admin.editManageStock(Admin.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editManageStock -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:smartChainTestCase.Admin@298a5e20]" started-at="2024-11-26T10:54:16 IST" name="closeBrowser" finished-at="2024-11-26T10:54:16 IST" duration-ms="257" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[=====BROWSER IS CLOSED======]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- smartChainTestCase.Admin -->
      <class name="smartChainTestCase.Retailer">
        <test-method is-config="true" signature="launchBrowser(java.lang.String)[pri:0, instance:smartChainTestCase.Retailer@1ed4ae0f]" started-at="2024-11-26T10:54:16 IST" name="launchBrowser" finished-at="2024-11-26T10:54:19 IST" duration-ms="2311" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[====CHROME IS LAUNCHED SUCCESSFULLY====]]>
            </line>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="order_Manufacturer()[pri:0, instance:smartChainTestCase.Retailer@1ed4ae0f]" started-at="2024-11-26T10:54:19 IST" name="order_Manufacturer" finished-at="2024-11-26T10:54:36 IST" duration-ms="17441" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"xpath","selector":"//input[@value='Log out']"}
  (Session info: chrome=131.0.6778.71)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.12.0', revision: '249f2a7d1b*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [7666dc6bebadde69f02037b085d18ed6, findElement {using=xpath, value=//input[@value='Log out']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.71, chrome: {chromedriverVersion: 131.0.6778.85 (3d81e41b6f3a..., userDataDir: C:\Users\Ranjith\AppData\Lo...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:58438}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:58438/devtoo..., se:cdpVersion: 131.0.6778.71, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 7666dc6bebadde69f02037b085d18ed6]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@value='Log out']"}
  (Session info: chrome=131.0.6778.71)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.12.0', revision: '249f2a7d1b*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [7666dc6bebadde69f02037b085d18ed6, findElement {using=xpath, value=//input[@value='Log out']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.71, chrome: {chromedriverVersion: 131.0.6778.85 (3d81e41b6f3a..., userDataDir: C:\Users\Ranjith\AppData\Lo...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:58438}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:58438/devtoo..., se:cdpVersion: 131.0.6778.71, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 7666dc6bebadde69f02037b085d18ed6
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:359)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy20.click(Unknown Source)
at smartChainTestCase.Retailer.order_Manufacturer(Retailer.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
            <line>
              <![CDATA[======Login is Successfull=====]]>
            </line>
            <line>
              <![CDATA[order is posted successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- order_Manufacturer -->
        <test-method signature="retailer_myorders()[pri:0, instance:smartChainTestCase.Retailer@1ed4ae0f]" started-at="2024-11-26T10:54:36 IST" name="retailer_myorders" finished-at="2024-11-26T10:54:36 IST" duration-ms="14" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title miss match! expected [Login] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title miss match! expected [Login] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.SCM.assertUtility.Assertutility.verifyTitle(Assertutility.java:33)
at smartChainTestCase.Retailer.retailer_myorders(Retailer.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- retailer_myorders -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:smartChainTestCase.Retailer@1ed4ae0f]" started-at="2024-11-26T10:54:36 IST" name="closeBrowser" finished-at="2024-11-26T10:54:36 IST" duration-ms="257" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[=====BROWSER IS CLOSED======]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- smartChainTestCase.Retailer -->
    </test> <!-- TestRunner_Chrome -->
  </suite> <!-- crossBrowserSuite -->
</testng-results>
